name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        
    - name: Run unit tests
      run: |
        pytest tests/ -m "unit" -v --cov --cov-report=xml
        
    - name: Upload unit test coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unit
        name: unit-tests

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        
    - name: Run integration tests
      run: |
        pytest tests/ -m "integration" -v --cov --cov-report=xml
        
    - name: Upload integration test coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: integration
        name: integration-tests

  priority-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        priority: [critical, high, medium, low]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        
    - name: Run ${{ matrix.priority }} priority tests
      run: |
        pytest tests/ -m "${{ matrix.priority }}" -v --cov --cov-report=xml
        
    - name: Upload ${{ matrix.priority }} test coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: ${{ matrix.priority }}
        name: ${{ matrix.priority }}-tests

  all-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, priority-tests]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        
    - name: Run all tests
      run: |
        pytest tests/simple_test_eventhub_producer.py tests/simple_test_eventhub_listener.py tests/simple_test_bronze_to_silver_dqx.py -v --cov --cov-report=xml --junit-xml=test-results.xml
        
    - name: Upload complete test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          test-results.xml
          coverage.xml
          htmlcov/
        
    - name: Upload final coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: complete
        name: all-tests